### ISSUE TITLE
Issue after adding validation of textFields in User Login page.

### ISSUE THREAD

**Issue by realakashdeep** [realakashdeep/Digital-Health-Care-Application#1]
When the validation fails, the textFields for both Password and Phone Number, the height of both the fields are getting smaller as compared to before failing the validation.

**Comment by Sushantlama** [comment]
![image](https://github.com/realakashdeep/Digital-Health-Care-Application/assets/76801926/8c056b15-5703-497e-ac2e-4c1ab3bc1e72)
